[project]
name = "shiver"
description = "Spectroscopy Histogram Visualizer for Event Reduction"
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "mantidworkbench"
]

[build-system]
requires = [
  "setuptools >= 42",
  "versioningit"
]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[project.gui-scripts]
shiver = "shiver:main"
